version: '3'
services:
  api:
    build: ./
    depends_on:
      - "postgres"
    env_file:
      - .variables.env
    ports:
      - "8085:80"
    networks:
      default:

  postgres:
    image: postgres
    env_file:
      - .variables.env
    networks:
      default:

